### ISSUE TITLE
Can't run any examples

### ISSUE THREAD

**Issue by bpmsilva** [TUD-RST/pytrajectory#3] opened 2019-03-03 06:13 UTC
I'm trying to simply run an example. After installation, here is what I am doing:
1. Cloning the repository
2. Moving the examples files from examples folder to pytrajectory folder.
3. Running, inside the pytrajectory folder, "python2 ex0_InvertedPendulumSwingUp.py"
However I get a "ValueError: max() arg is an empty sequence"

Here is the Traceback:
WARNING: 	 scipy version (1.2.1) may be out of date
WARNING: 	 sympy version (1.3) may be out of date
Traceback (most recent call last):
  File "ex0_InvertedPendulumSwingUp.py", line 44, in <module>
    S = ControlSystem(f, a, b, xa, xb, ua, ub, kx=5, use_chains=False)
  File "/usr/local/lib/python2.7/dist-packages/pytrajectory/system.py", line 89, in __init__
    self.eqs = CollocationSystem(sys=self.dyn_sys, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytrajectory/collocation.py", line 53, in __init__
    self._Df_vectorized = sym2num_vectorfield(Df, sys.states, sys.inputs, vectorized=True, cse=True)
  File "/usr/local/lib/python2.7/dist-packages/pytrajectory/auxiliary.py", line 286, in sym2num_vectorfield
    modules=[{'ImmutableMatrix':np.array}, 'numpy'])
  File "/usr/local/lib/python2.7/dist-packages/pytrajectory/auxiliary.py", line 420, in cse_lambdify
    cse_pairs, red_exprs = sp.cse(expr, symbols=sp.numbered_symbols('r'))
  File "/usr/local/lib/python2.7/dist-packages/sympy/simplify/cse_main.py", line 726, in cse
    opt_subs = opt_cse(reduced_exprs, order)
  File "/usr/local/lib/python2.7/dist-packages/sympy/simplify/cse_main.py", line 467, in opt_cse
    match_common_args(Mul, commutative_muls, opt_subs)
  File "/usr/local/lib/python2.7/dist-packages/sympy/simplify/cse_main.py", line 316, in match_common_args
    arg_tracker.func_to_argset[i], min_func_i=i + 1)
  File "/usr/local/lib/python2.7/dist-packages/sympy/simplify/cse_main.py", line 204, in get_common_arg_candidates
    largest_funcset = max(funcsets, key=len)
ValueError: max() arg is an empty sequence

Does someone have any ideas what I am doing wrong?

**Comment by cknoll** [comment] 2019-03-04 11:49
I can confirm the error. I seems it was introduced due to a behavior-change in sympy (from 1.1 to 1.2).

Quick workarround: `pip install sympy==1.1`(best use a virtual environment or conda env).


I try to solve the actual reason for this issue.

**Comment by cknoll** [comment] 2019-03-04 13:57
I just tried out the develop branch. I worked for the two tested examples (also with new sympy >1.2). Probably the issue has been resolved by the refactoring work which has been done in the development branch.

If it works also for you, then I would make a new release.

**Comment by bpmsilva** [comment] 2019-03-04 21:28
Thanks for the quick answer.

I couldn't downgrade sympy on my linux machine (maybe I'll try later on windows), so I tried the development branch alternative. However, the "TransitionProblem" module is missing. I think the remote branch is out of sync with your local branch. Could you confirm it and correct it?

Thanks in advance

**Comment by cknoll** [comment] 2019-03-05 15:50
> I couldn't downgrade sympy on my linux machine

For such cases virtual env is really good. While I ignored recommendations of colleagues for quite some time, now I use it intensively and can **really recommend** it. Its main purpose is to have different versions of packages (and python itself) on the same system. See e.g.
- https://virtualenv.pypa.io/en/stable/userguide/
- https://realpython.com/python-virtual-environments-a-primer/

>  I think the remote branch is out of sync with your local branch. Could you confirm it and correct it?

I double checked and it is in sync.

> However, the "TransitionProblem" module is missing

This is a little bit strange. `TransitionProblem` is the main class which was called `ControlSystem` in master. It seems like you have run the example from the develop branch with the library from the (old) master branch. Maybe you can **completely uninstall Pytrajectory first** and then install it from the develop branch with `pip install -e .` (inside a venv) or `pip install --user -e .` (without venv)

To find out where your current installation of Pytrajectory lives, you can use:
```python
import pytrajectory
print(pytrajectory.__file__)
```

**Comment by bpmsilva** [comment] 2019-03-06 07:26
Not sure exactly how (I'm newbie to Python), but it worked!

Here is what I did:
1. I uninstalled pytrajectory
2. I installed ipydex (it was missing)
3. I ran "pip install --user -e ."

I'll dive now into your code to understand it better. I'll also consider using the virtual environments.

Thanks for the attention!

**Comment by cknoll** [comment] 2019-03-06 09:28
If you really want to dive into the code, some remarks:
- Be sure to use the develop branch.
- The codebase was written by four people (three engineering students and me) over several years with different programming skills and tastes.
- The codebase contains some residues of old experiments which seemed promising but eventually turned out to be not that useful
- Use a tool which supports navigating through a large codebase. I use pycharm and especially CTRL-click and "Find Usages" for navigation.
- We tried to cover the main ideas with documentation and comments. But with limited time its hard to keep that in sync with the code. So not every feature is documented. Comments should mostly be OK.
- `ipydex.IPS()` (embedded ipython) might be useful to explore a current situation and understand whats going on. I often prefer it over a debugger because you can interactively try out things.

**Closed as completed by cknoll** 2019-03-06 09:28 UTC
Labels: bug

**Comment by cknoll** [comment] 2019-04-03 16:18
FYI: I recently merged develop branch into master.
